var annotated_dup =
[
    [ "logit", "namespacelogit.html", [
      [ "detail", "namespacelogit_1_1detail.html", [
        [ "CompressionWorker", "classlogit_1_1detail_1_1CompressionWorker.html", "classlogit_1_1detail_1_1CompressionWorker" ],
        [ "MdbxByteReader", "classlogit_1_1detail_1_1MdbxByteReader.html", "classlogit_1_1detail_1_1MdbxByteReader" ],
        [ "MdbxByteWriter", "classlogit_1_1detail_1_1MdbxByteWriter.html", "classlogit_1_1detail_1_1MdbxByteWriter" ],
        [ "MdbxReadException", "classlogit_1_1detail_1_1MdbxReadException.html", "classlogit_1_1detail_1_1MdbxReadException" ],
        [ "MpscRingAny", "classlogit_1_1detail_1_1MpscRingAny.html", "classlogit_1_1detail_1_1MpscRingAny" ],
        [ "ScopeTimer", "classlogit_1_1detail_1_1ScopeTimer.html", "classlogit_1_1detail_1_1ScopeTimer" ],
        [ "SingleThreadExecutor", "classlogit_1_1detail_1_1SingleThreadExecutor.html", "classlogit_1_1detail_1_1SingleThreadExecutor" ],
        [ "TaskExecutor", "classlogit_1_1detail_1_1TaskExecutor.html", "classlogit_1_1detail_1_1TaskExecutor" ]
      ] ],
      [ "BufferedLogEntry", "structlogit_1_1BufferedLogEntry.html", "structlogit_1_1BufferedLogEntry" ],
      [ "ConsoleLogger", "classlogit_1_1ConsoleLogger.html", "classlogit_1_1ConsoleLogger" ],
      [ "ConsoleStreamRoute", "structlogit_1_1ConsoleStreamRoute.html", "structlogit_1_1ConsoleStreamRoute" ],
      [ "CrashPosixLogger", "classlogit_1_1CrashPosixLogger.html", "classlogit_1_1CrashPosixLogger" ],
      [ "CrashWindowsLogger", "classlogit_1_1CrashWindowsLogger.html", "classlogit_1_1CrashWindowsLogger" ],
      [ "EventLogLogger", "classlogit_1_1EventLogLogger.html", "classlogit_1_1EventLogLogger" ],
      [ "FileLogger", "classlogit_1_1FileLogger.html", "classlogit_1_1FileLogger" ],
      [ "FormatInstruction", "structlogit_1_1FormatInstruction.html", "structlogit_1_1FormatInstruction" ],
      [ "ILogFormatter", "classlogit_1_1ILogFormatter.html", "classlogit_1_1ILogFormatter" ],
      [ "ILogger", "classlogit_1_1ILogger.html", "classlogit_1_1ILogger" ],
      [ "ILogReader", "classlogit_1_1ILogReader.html", "classlogit_1_1ILogReader" ],
      [ "ILogSubscriber", "classlogit_1_1ILogSubscriber.html", "classlogit_1_1ILogSubscriber" ],
      [ "LogClearOptions", "structlogit_1_1LogClearOptions.html", "structlogit_1_1LogClearOptions" ],
      [ "LogClearResult", "structlogit_1_1LogClearResult.html", "structlogit_1_1LogClearResult" ],
      [ "LogFileInfo", "structlogit_1_1LogFileInfo.html", "structlogit_1_1LogFileInfo" ],
      [ "LogFileReadResult", "structlogit_1_1LogFileReadResult.html", "structlogit_1_1LogFileReadResult" ],
      [ "Logger", "classlogit_1_1Logger.html", "classlogit_1_1Logger" ],
      [ "LogRecord", "structlogit_1_1LogRecord.html", "structlogit_1_1LogRecord" ],
      [ "LogRecordSnapshot", "structlogit_1_1LogRecordSnapshot.html", "structlogit_1_1LogRecordSnapshot" ],
      [ "LogStream", "classlogit_1_1LogStream.html", "classlogit_1_1LogStream" ],
      [ "MdbxLogger", "classlogit_1_1MdbxLogger.html", "classlogit_1_1MdbxLogger" ],
      [ "MemoryLogger", "classlogit_1_1MemoryLogger.html", "classlogit_1_1MemoryLogger" ],
      [ "OtlpHttpLogger", "classlogit_1_1OtlpHttpLogger.html", "classlogit_1_1OtlpHttpLogger" ],
      [ "OtlpHttpLoggerState", "structlogit_1_1OtlpHttpLoggerState.html", "structlogit_1_1OtlpHttpLoggerState" ],
      [ "OtlpJsonFormatConfig", "structlogit_1_1OtlpJsonFormatConfig.html", "structlogit_1_1OtlpJsonFormatConfig" ],
      [ "OtlpLogItem", "structlogit_1_1OtlpLogItem.html", "structlogit_1_1OtlpLogItem" ],
      [ "OtlpPayloadLogger", "classlogit_1_1OtlpPayloadLogger.html", "classlogit_1_1OtlpPayloadLogger" ],
      [ "OtlpRecordSnapshot", "structlogit_1_1OtlpRecordSnapshot.html", "structlogit_1_1OtlpRecordSnapshot" ],
      [ "PathComponents", "structlogit_1_1PathComponents.html", "structlogit_1_1PathComponents" ],
      [ "PatternCompiler", "classlogit_1_1PatternCompiler.html", "classlogit_1_1PatternCompiler" ],
      [ "PrometheusHttpServerLogger", "classlogit_1_1PrometheusHttpServerLogger.html", "classlogit_1_1PrometheusHttpServerLogger" ],
      [ "PrometheusLabel", "structlogit_1_1PrometheusLabel.html", "structlogit_1_1PrometheusLabel" ],
      [ "PrometheusLoggerMetrics", "classlogit_1_1PrometheusLoggerMetrics.html", "classlogit_1_1PrometheusLoggerMetrics" ],
      [ "PrometheusMetricFamily", "structlogit_1_1PrometheusMetricFamily.html", "structlogit_1_1PrometheusMetricFamily" ],
      [ "PrometheusPayloadLogger", "classlogit_1_1PrometheusPayloadLogger.html", "classlogit_1_1PrometheusPayloadLogger" ],
      [ "PrometheusRegistry", "classlogit_1_1PrometheusRegistry.html", "classlogit_1_1PrometheusRegistry" ],
      [ "PrometheusSample", "structlogit_1_1PrometheusSample.html", "structlogit_1_1PrometheusSample" ],
      [ "PrometheusTextFormatConfig", "structlogit_1_1PrometheusTextFormatConfig.html", "structlogit_1_1PrometheusTextFormatConfig" ],
      [ "SimpleLogFormatter", "classlogit_1_1SimpleLogFormatter.html", "classlogit_1_1SimpleLogFormatter" ],
      [ "SyslogLogger", "classlogit_1_1SyslogLogger.html", "classlogit_1_1SyslogLogger" ],
      [ "UniqueFileLogger", "classlogit_1_1UniqueFileLogger.html", "classlogit_1_1UniqueFileLogger" ],
      [ "VariableValue", "structlogit_1_1VariableValue.html", "structlogit_1_1VariableValue" ],
      [ "WindowsDebugLogger", "classlogit_1_1WindowsDebugLogger.html", "classlogit_1_1WindowsDebugLogger" ]
    ] ],
    [ "CustomErrorCategory", "classCustomErrorCategory.html", "classCustomErrorCategory" ]
];