var hierarchy =
[
    [ "logit::BufferedLogEntry", "structlogit_1_1BufferedLogEntry.html", null ],
    [ "logit::detail::MpscRingAny< T >::Cell", "structlogit_1_1detail_1_1MpscRingAny_1_1Cell.html", null ],
    [ "logit::detail::CompressionWorker", "classlogit_1_1detail_1_1CompressionWorker.html", null ],
    [ "logit::ConsoleLogger::Config", "structlogit_1_1ConsoleLogger_1_1Config.html", null ],
    [ "logit::CrashPosixLogger::Config", "structlogit_1_1CrashPosixLogger_1_1Config.html", null ],
    [ "logit::CrashWindowsLogger::Config", "structlogit_1_1CrashWindowsLogger_1_1Config.html", null ],
    [ "logit::EventLogLogger::Config", "structlogit_1_1EventLogLogger_1_1Config.html", null ],
    [ "logit::FileLogger::Config", "structlogit_1_1FileLogger_1_1Config.html", null ],
    [ "logit::MdbxLogger::Config", "structlogit_1_1MdbxLogger_1_1Config.html", null ],
    [ "logit::MemoryLogger::Config", "structlogit_1_1MemoryLogger_1_1Config.html", null ],
    [ "logit::OtlpHttpLogger::Config", "structlogit_1_1OtlpHttpLogger_1_1Config.html", null ],
    [ "logit::OtlpPayloadLogger::Config", "structlogit_1_1OtlpPayloadLogger_1_1Config.html", null ],
    [ "logit::PrometheusHttpServerLogger::Config", "structlogit_1_1PrometheusHttpServerLogger_1_1Config.html", null ],
    [ "logit::PrometheusPayloadLogger::Config", "structlogit_1_1PrometheusPayloadLogger_1_1Config.html", null ],
    [ "logit::SimpleLogFormatter::Config", "structlogit_1_1SimpleLogFormatter_1_1Config.html", null ],
    [ "logit::SyslogLogger::Config", "structlogit_1_1SyslogLogger_1_1Config.html", null ],
    [ "logit::UniqueFileLogger::Config", "structlogit_1_1UniqueFileLogger_1_1Config.html", null ],
    [ "logit::WindowsDebugLogger::Config", "structlogit_1_1WindowsDebugLogger_1_1Config.html", null ],
    [ "logit::ConsoleStreamRoute", "structlogit_1_1ConsoleStreamRoute.html", null ],
    [ "logit::PrometheusRegistry::Entry", "structlogit_1_1PrometheusRegistry_1_1Entry.html", null ],
    [ "std::error_category", null, [
      [ "CustomErrorCategory", "classCustomErrorCategory.html", null ]
    ] ],
    [ "logit::FileLogger::FileSortKey", "structlogit_1_1FileLogger_1_1FileSortKey.html", null ],
    [ "logit::FormatInstruction", "structlogit_1_1FormatInstruction.html", null ],
    [ "logit::ILogFormatter", "classlogit_1_1ILogFormatter.html", [
      [ "logit::SimpleLogFormatter", "classlogit_1_1SimpleLogFormatter.html", null ]
    ] ],
    [ "logit::ILogger", "classlogit_1_1ILogger.html", [
      [ "logit::ConsoleLogger", "classlogit_1_1ConsoleLogger.html", null ],
      [ "logit::CrashPosixLogger", "classlogit_1_1CrashPosixLogger.html", null ],
      [ "logit::CrashWindowsLogger", "classlogit_1_1CrashWindowsLogger.html", null ],
      [ "logit::EventLogLogger", "classlogit_1_1EventLogLogger.html", null ],
      [ "logit::FileLogger", "classlogit_1_1FileLogger.html", null ],
      [ "logit::MdbxLogger", "classlogit_1_1MdbxLogger.html", null ],
      [ "logit::MemoryLogger", "classlogit_1_1MemoryLogger.html", null ],
      [ "logit::OtlpHttpLogger", "classlogit_1_1OtlpHttpLogger.html", null ],
      [ "logit::OtlpPayloadLogger", "classlogit_1_1OtlpPayloadLogger.html", null ],
      [ "logit::PrometheusHttpServerLogger", "classlogit_1_1PrometheusHttpServerLogger.html", null ],
      [ "logit::PrometheusPayloadLogger", "classlogit_1_1PrometheusPayloadLogger.html", null ],
      [ "logit::SyslogLogger", "classlogit_1_1SyslogLogger.html", null ],
      [ "logit::UniqueFileLogger", "classlogit_1_1UniqueFileLogger.html", null ],
      [ "logit::WindowsDebugLogger", "classlogit_1_1WindowsDebugLogger.html", null ]
    ] ],
    [ "logit::ILogReader", "classlogit_1_1ILogReader.html", [
      [ "logit::MdbxLogger", "classlogit_1_1MdbxLogger.html", null ],
      [ "logit::MemoryLogger", "classlogit_1_1MemoryLogger.html", null ]
    ] ],
    [ "logit::ILogSubscriber", "classlogit_1_1ILogSubscriber.html", [
      [ "logit::MdbxLogger", "classlogit_1_1MdbxLogger.html", null ],
      [ "logit::MemoryLogger", "classlogit_1_1MemoryLogger.html", null ]
    ] ],
    [ "logit::LogClearOptions", "structlogit_1_1LogClearOptions.html", null ],
    [ "logit::LogClearResult", "structlogit_1_1LogClearResult.html", null ],
    [ "logit::LogFileInfo", "structlogit_1_1LogFileInfo.html", null ],
    [ "logit::LogFileReadResult", "structlogit_1_1LogFileReadResult.html", null ],
    [ "logit::Logger", "classlogit_1_1Logger.html", null ],
    [ "logit::Logger::LoggerStrategy", "structlogit_1_1Logger_1_1LoggerStrategy.html", null ],
    [ "logit::LogRecord", "structlogit_1_1LogRecord.html", null ],
    [ "logit::LogRecordSnapshot", "structlogit_1_1LogRecordSnapshot.html", null ],
    [ "logit::LogStream", "classlogit_1_1LogStream.html", null ],
    [ "logit::detail::MdbxByteReader", "classlogit_1_1detail_1_1MdbxByteReader.html", null ],
    [ "logit::detail::MdbxByteWriter", "classlogit_1_1detail_1_1MdbxByteWriter.html", null ],
    [ "logit::MdbxLogger::MdbxLogItem", "structlogit_1_1MdbxLogger_1_1MdbxLogItem.html", null ],
    [ "logit::detail::MpscRingAny< T >", "classlogit_1_1detail_1_1MpscRingAny.html", null ],
    [ "logit::OtlpHttpLoggerState", "structlogit_1_1OtlpHttpLoggerState.html", null ],
    [ "logit::OtlpJsonFormatConfig", "structlogit_1_1OtlpJsonFormatConfig.html", null ],
    [ "logit::OtlpLogItem", "structlogit_1_1OtlpLogItem.html", null ],
    [ "logit::OtlpRecordSnapshot", "structlogit_1_1OtlpRecordSnapshot.html", null ],
    [ "logit::PathComponents", "structlogit_1_1PathComponents.html", null ],
    [ "logit::PatternCompiler", "classlogit_1_1PatternCompiler.html", null ],
    [ "logit::MdbxLogger::Payload", "structlogit_1_1MdbxLogger_1_1Payload.html", null ],
    [ "logit::MdbxLogger::PayloadView", "structlogit_1_1MdbxLogger_1_1PayloadView.html", null ],
    [ "logit::ConsoleLogger::PendingEnqueue", "classlogit_1_1ConsoleLogger_1_1PendingEnqueue.html", null ],
    [ "logit::PrometheusLabel", "structlogit_1_1PrometheusLabel.html", null ],
    [ "logit::PrometheusLoggerMetrics", "classlogit_1_1PrometheusLoggerMetrics.html", null ],
    [ "logit::PrometheusMetricFamily", "structlogit_1_1PrometheusMetricFamily.html", null ],
    [ "logit::PrometheusRegistry", "classlogit_1_1PrometheusRegistry.html", null ],
    [ "logit::PrometheusSample", "structlogit_1_1PrometheusSample.html", null ],
    [ "logit::PrometheusTextFormatConfig", "structlogit_1_1PrometheusTextFormatConfig.html", null ],
    [ "logit::MdbxLogger::Record", "structlogit_1_1MdbxLogger_1_1Record.html", null ],
    [ "std::runtime_error", null, [
      [ "logit::detail::MdbxReadException", "classlogit_1_1detail_1_1MdbxReadException.html", null ]
    ] ],
    [ "logit::detail::ScopeTimer", "classlogit_1_1detail_1_1ScopeTimer.html", null ],
    [ "logit::MdbxLogger::Session", "structlogit_1_1MdbxLogger_1_1Session.html", null ],
    [ "logit::MdbxLogger::SessionView", "structlogit_1_1MdbxLogger_1_1SessionView.html", null ],
    [ "logit::detail::SingleThreadExecutor", "classlogit_1_1detail_1_1SingleThreadExecutor.html", null ],
    [ "logit::detail::TaskExecutor", "classlogit_1_1detail_1_1TaskExecutor.html", null ],
    [ "logit::UniqueFileLogger::ThreadLogInfo", "structlogit_1_1UniqueFileLogger_1_1ThreadLogInfo.html", null ],
    [ "logit::UniqueFileLogger::UniqueFileSortKey", "structlogit_1_1UniqueFileLogger_1_1UniqueFileSortKey.html", null ],
    [ "logit::VariableValue", "structlogit_1_1VariableValue.html", null ]
];